language: java

#script: "mvn cobertura:cobertura"
script: "mvn clean test"
#script: "mvn test"

after_success:
  - codecov
#  - bash -f /target/surefire-reports
#  - bash <(curl -s https://codecov.io/bash)


