language: java

script: "mvn cobertura:cobertura"


after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
      name: "Jupiter Starter Sample: Maven"
      script: cd $TRAVIS_BUILD_DIR/
 
