codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
require_changes: no

ignore:
  - "src/main/java/Components/**/*"
  - "src/main/java/Client/Authentication.java"
  - "src/main/java/Client/CourseView.java "
  - "src/main/java/Client/CreateQuestionView.java"
  - "src/main/java/Client/ExportView.java"
  - "src/main/java/Client/QuestionView.java "
#  - "path/to/folder"  # ignore folders and all its contents
#  - "test_*.rb"       # wildcards accepted
#  - "**/*.py"         # glob accepted
#  - "[a-z]+/test_.*"  # regexp accepted
